
word = input('type something:')
print("It's alphabet:")
print(word.isalpha())
print('Is number:')
print(word.isnumeric())
print("It's number and alphabet:")
print(word.isalnum())
print("It's capitalized words:")
print(word.isupper())
print("It's tiny words:")
print(word.islower())
print("It's just spaces:")
print(word.isspace())
print('Is capitalized:')
print(word.istitle())
