x = input('digite algo:')
print('É alfabeto:')
print(x.isalpha())
print('É numero:')
print(x.isnumeric())
print('É numero e alfabeto:')
print(x.isalnum())
print('É palavra em maiuscula:')
print(x.isupper())
print('É palavra em minusculo:')
print(x.islower())
print('É so tem espaços:')
print(x.isspace())
print('É capitalizada:')
print(x.istitle())
